name: Run Minileagues Script

on:
  schedule:
    # Run every 5 minutes between 7am-9pm UTC (8am-10pm BST)
    # BST is UTC+1, so 8am BST = 7am UTC, 10pm BST = 9pm UTC
    - cron: '*/5 7-21 * * *'
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true
      
      - name: Run minileagues script
        run: deno run --allow-net --allow-read --allow-write minileagues/src/index.ts
        
      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update minileagues data - $(date)"
            git push
          fi